version: '3.6'
services:
  postgres:
    image: postgres:12
    ports:
      - "5433:5432"
    restart: always
    volumes:
    - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      POSTGRES_PASSWORD: postgres